### PR TITLE
master-qa-60422

### PR DESCRIPTION
**Pull request by dellawang**
https://issues.liferay.com/browse/LRQA-60422

@gaborlovasdotcom @xbrianlee

### CODE REVIEW

**Comment by dellawang** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
ci:bundle

**Comment by dellawang** [comment]
ci:test:security

**Comment by dellawang** [comment]
ci:test:security

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:security

**Comment by dellawang** [comment]
ci:forward

**Comment by dellawang** [comment]
ci:stop

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:forward

**Comment by dellawang** [comment]
ci:stop

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:forward

**Pull request closed without merging**
